document.addEventListener('DOMContentLoaded', function () {
    const carMeetCategories = [
        "Elegy Meet",
        "F1 Cars",
        "JDM Cars",
        "German Cars",
        "American Cars",
        "French Cars",
        "Dream Cars",
        "Euro Cars",
        "Budget Cars",
        "Track Cars",
        "British Cars",
        "Hypercar Meet",
        "EV Meet",
        "Modern Muscle",
        "Classic Muscle",
        "Pickup Trucks",
        "V12 Cars",
        "Blowers",
        "Rusty",
        "BBS Rims",
        "TE37s",
        "Street Wheels",
        "Russian Car Meet",
        "Daddys Money Meet",
        "Touring Car Meet",
        "RWB meet",
        "College Budget & Daily",
        "Drift Cars",
        "Southern San Andreas Super Autos Meet",
        "Hot Hatch",
        "Midnight Club Meet",
        "Wagon/Hatchback Meet",
        "Underrated Cars Meet",
        "Sleeper",
        "Pop Up Headlights",
        "AWD Cars",
        "FWD Cars",
        "RWD Cars",
        "Road Trip",
        "Beach",
        "Daily Drivers",
        "Special & Armored Cars",
        "Slammed",
        "Gumball 3000",
        "StanceWars",
        "Ricer",
        "Drug Running",
        "Mafia",
        "Hot Rod",
        "Big Wang",
        "American Showdown",
        "Need for Speed",
        "Clean",
        "Offroad",
        "Widebody",
        "Movie Cars",
        "Fast n Furious",
        "Cars & Coffee",
        "Luxury Meet",
        "Supercar Meet",
        "Tuner Meet",
        "Super",
        "Sports Cars",
        "Sports Classics",
        "Coupes",
        "Muscle",
        "Sedan",
        "Compacts",
        "SUV",
        "Off-Road Vehicles",
        "Motorcycles",
        "Ocelot",
        "Dinka",
        "Grotti",
        "Enus",
        "Bimmer Meet",
        "McLaren Meet",
        "Ferarri Club Car",
        "Toyota Meet",
        "Koenigsegg vs Bugatti",
        "Classic vs Modern Supercars",
        "Ford vS Ferrari",
        "Domestic vs Imports",
        "Ferrari vS Lamborghini",
        "Germany vs Britain",
        "Rolls vs Bentley",
        "Supra vs Skyline",
        "German vs Japan",
        "Grotti VS Pegassi",
        "Grove Street VS Ballas",
        "Jaguar vs Aston Martin",
        "Touge",
        "Rally",
        "Drift",
        "50s",
        "60s",
        "70s",
        "80s",
        "90s",
        "2000s",
        "Shades of Blue",
        "Pastel Colors",
        "Dark Colors Meet",
        "Black & White",
        "Red vs Blue"
      ];
      
  
    const randomButton = document.getElementById('randomButton');
    const randomWordDisplay = document.getElementById('randomWordDisplay');
  
    randomButton.addEventListener('click', function () {
      const randomIndex = Math.floor(Math.random() * carMeetCategories.length);
      const randomWord = carMeetCategories[randomIndex];
      randomWordDisplay.textContent = `Random Theme: ${randomWord}`;
    });
  });
  